package actions

import (

  "github.com/pkg/errors"
  "github.com/gobuffalo/buffalo"
  "github.com/gobuffalo/pop"
  "github.com/myWebsite/golang/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Comment)
// DB Table: Plural (comments)
// Resource: Plural (Comments)
// Path: Plural (/comments)
// View Template Folder: Plural (/templates/comments/)

// CommentsResource is the resource for the Comment model
type CommentsResource struct{
  buffalo.Resource
}

// List gets all Comments. This function is mapped to the path
// GET /comments
func (v CommentsResource) List(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return errors.WithStack(errors.New("no transaction found"))
  }

  comments := &models.Comments{}

  // Paginate results. Params "page" and "per_page" control pagination.
  // Default values are "page=1" and "per_page=20".
  q := tx.PaginateFromParams(c.Params())

  // Retrieve all Comments from the DB
  if err := q.All(comments); err != nil {
    return errors.WithStack(err)
  }

  // Add the paginator to the context so it can be used in the template.
  c.Set("pagination", q.Paginator)

  return c.Render(200, r.Auto(c, comments))
}

// Show gets the data for one Comment. This function is mapped to
// the path GET /comments/{comment_id}
func (v CommentsResource) Show(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return errors.WithStack(errors.New("no transaction found"))
  }

  // Allocate an empty Comment
  comment := &models.Comment{}

  // To find the Comment the parameter comment_id is used.
  if err := tx.Find(comment, c.Param("comment_id")); err != nil {
    return c.Error(404, err)
  }

  return c.Render(200, r.Auto(c, comment))
}

// New renders the form for creating a new Comment.
// This function is mapped to the path GET /comments/new
func (v CommentsResource) New(c buffalo.Context) error {
  return c.Render(200, r.Auto(c, &models.Comment{}))
}
// Create adds a Comment to the DB. This function is mapped to the
// path POST /comments
func (v CommentsResource) Create(c buffalo.Context) error {
  // Allocate an empty Comment
  comment := &models.Comment{}

  // Bind comment to the html form elements
  if err := c.Bind(comment); err != nil {
    return errors.WithStack(err)
  }

  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return errors.WithStack(errors.New("no transaction found"))
  }

  // Validate the data from the html form
  verrs, err := tx.ValidateAndCreate(comment)
  if err != nil {
    return errors.WithStack(err)
  }

  if verrs.HasAny() {
    // Make the errors available inside the html template
    c.Set("errors", verrs)

    // Render again the new.html template that the user can
    // correct the input.
    return c.Render(422, r.Auto(c, comment))
  }

  // If there are no errors set a success message
  c.Flash().Add("success", T.Translate(c, "comment.created.success"))
  // and redirect to the comments index page
  return c.Render(201, r.Auto(c, comment))
}

// Edit renders a edit form for a Comment. This function is
// mapped to the path GET /comments/{comment_id}/edit
func (v CommentsResource) Edit(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return errors.WithStack(errors.New("no transaction found"))
  }

  // Allocate an empty Comment
  comment := &models.Comment{}

  if err := tx.Find(comment, c.Param("comment_id")); err != nil {
    return c.Error(404, err)
  }

  return c.Render(200, r.Auto(c, comment))
}
// Update changes a Comment in the DB. This function is mapped to
// the path PUT /comments/{comment_id}
func (v CommentsResource) Update(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return errors.WithStack(errors.New("no transaction found"))
  }

  // Allocate an empty Comment
  comment := &models.Comment{}

  if err := tx.Find(comment, c.Param("comment_id")); err != nil {
    return c.Error(404, err)
  }

  // Bind Comment to the html form elements
  if err := c.Bind(comment); err != nil {
    return errors.WithStack(err)
  }

  verrs, err := tx.ValidateAndUpdate(comment)
  if err != nil {
    return errors.WithStack(err)
  }

  if verrs.HasAny() {
    // Make the errors available inside the html template
    c.Set("errors", verrs)

    // Render again the edit.html template that the user can
    // correct the input.
    return c.Render(422, r.Auto(c, comment))
  }

  // If there are no errors set a success message
  c.Flash().Add("success", T.Translate(c, "comment.updated.success"))
  // and redirect to the comments index page
  return c.Render(200, r.Auto(c, comment))
}

// Destroy deletes a Comment from the DB. This function is mapped
// to the path DELETE /comments/{comment_id}
func (v CommentsResource) Destroy(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return errors.WithStack(errors.New("no transaction found"))
  }

  // Allocate an empty Comment
  comment := &models.Comment{}

  // To find the Comment the parameter comment_id is used.
  if err := tx.Find(comment, c.Param("comment_id")); err != nil {
    return c.Error(404, err)
  }

  if err := tx.Destroy(comment); err != nil {
    return errors.WithStack(err)
  }

  // If there are no errors set a flash message
  c.Flash().Add("success", T.Translate(c, "comment.destroyed.success"))
  // Redirect to the comments index page
  return c.Render(200, r.Auto(c, comment))
}
