package actions

import (

  "github.com/pkg/errors"
  "github.com/gobuffalo/buffalo"
  "github.com/gobuffalo/pop"
  "github.com/myWebsite/golang/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (License)
// DB Table: Plural (licenses)
// Resource: Plural (Licenses)
// Path: Plural (/licenses)
// View Template Folder: Plural (/templates/licenses/)

// LicensesResource is the resource for the License model
type LicensesResource struct{
  buffalo.Resource
}

// List gets all Licenses. This function is mapped to the path
// GET /licenses
func (v LicensesResource) List(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return errors.WithStack(errors.New("no transaction found"))
  }

  licenses := &models.Licenses{}

  // Paginate results. Params "page" and "per_page" control pagination.
  // Default values are "page=1" and "per_page=20".
  q := tx.PaginateFromParams(c.Params())

  // Retrieve all Licenses from the DB
  if err := q.All(licenses); err != nil {
    return errors.WithStack(err)
  }

  // Add the paginator to the context so it can be used in the template.
  c.Set("pagination", q.Paginator)

  return c.Render(200, r.Auto(c, licenses))
}

// Show gets the data for one License. This function is mapped to
// the path GET /licenses/{license_id}
func (v LicensesResource) Show(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return errors.WithStack(errors.New("no transaction found"))
  }

  // Allocate an empty License
  license := &models.License{}

  // To find the License the parameter license_id is used.
  if err := tx.Find(license, c.Param("license_id")); err != nil {
    return c.Error(404, err)
  }

  return c.Render(200, r.Auto(c, license))
}

// New renders the form for creating a new License.
// This function is mapped to the path GET /licenses/new
func (v LicensesResource) New(c buffalo.Context) error {
  return c.Render(200, r.Auto(c, &models.License{}))
}
// Create adds a License to the DB. This function is mapped to the
// path POST /licenses
func (v LicensesResource) Create(c buffalo.Context) error {
  // Allocate an empty License
  license := &models.License{}

  // Bind license to the html form elements
  if err := c.Bind(license); err != nil {
    return errors.WithStack(err)
  }

  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return errors.WithStack(errors.New("no transaction found"))
  }

  // Validate the data from the html form
  verrs, err := tx.ValidateAndCreate(license)
  if err != nil {
    return errors.WithStack(err)
  }

  if verrs.HasAny() {
    // Make the errors available inside the html template
    c.Set("errors", verrs)

    // Render again the new.html template that the user can
    // correct the input.
    return c.Render(422, r.Auto(c, license))
  }

  // If there are no errors set a success message
  c.Flash().Add("success", T.Translate(c, "license.created.success"))
  // and redirect to the licenses index page
  return c.Render(201, r.Auto(c, license))
}

// Edit renders a edit form for a License. This function is
// mapped to the path GET /licenses/{license_id}/edit
func (v LicensesResource) Edit(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return errors.WithStack(errors.New("no transaction found"))
  }

  // Allocate an empty License
  license := &models.License{}

  if err := tx.Find(license, c.Param("license_id")); err != nil {
    return c.Error(404, err)
  }

  return c.Render(200, r.Auto(c, license))
}
// Update changes a License in the DB. This function is mapped to
// the path PUT /licenses/{license_id}
func (v LicensesResource) Update(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return errors.WithStack(errors.New("no transaction found"))
  }

  // Allocate an empty License
  license := &models.License{}

  if err := tx.Find(license, c.Param("license_id")); err != nil {
    return c.Error(404, err)
  }

  // Bind License to the html form elements
  if err := c.Bind(license); err != nil {
    return errors.WithStack(err)
  }

  verrs, err := tx.ValidateAndUpdate(license)
  if err != nil {
    return errors.WithStack(err)
  }

  if verrs.HasAny() {
    // Make the errors available inside the html template
    c.Set("errors", verrs)

    // Render again the edit.html template that the user can
    // correct the input.
    return c.Render(422, r.Auto(c, license))
  }

  // If there are no errors set a success message
  c.Flash().Add("success", T.Translate(c, "license.updated.success"))
  // and redirect to the licenses index page
  return c.Render(200, r.Auto(c, license))
}

// Destroy deletes a License from the DB. This function is mapped
// to the path DELETE /licenses/{license_id}
func (v LicensesResource) Destroy(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return errors.WithStack(errors.New("no transaction found"))
  }

  // Allocate an empty License
  license := &models.License{}

  // To find the License the parameter license_id is used.
  if err := tx.Find(license, c.Param("license_id")); err != nil {
    return c.Error(404, err)
  }

  if err := tx.Destroy(license); err != nil {
    return errors.WithStack(err)
  }

  // If there are no errors set a flash message
  c.Flash().Add("success", T.Translate(c, "license.destroyed.success"))
  // Redirect to the licenses index page
  return c.Render(200, r.Auto(c, license))
}
