package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/myWebsite/golang/models"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Github)
// DB Table: Plural (githubs)
// Resource: Plural (Githubs)
// Path: Plural (/githubs)
// View Template Folder: Plural (/templates/githubs/)

// GithubsResource is the resource for the Github model
type GithubsResource struct {
	buffalo.Resource
}

// List gets all Githubs. This function is mapped to the path
// GET /githubs
func (v GithubsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	githubs := &models.Githubs{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Githubs from the DB
	if err := q.All(githubs); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, githubs))
}

// Show gets the data for one Github. This function is mapped to
// the path GET /githubs/{github_id}
func (v GithubsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Github
	github := &models.Github{}

	// To find the Github the parameter github_id is used.
	if err := tx.Find(github, c.Param("github_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, github))
}

// New renders the form for creating a new Github.
// This function is mapped to the path GET /githubs/new
func (v GithubsResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Github{}))
}

// Create adds a Github to the DB. This function is mapped to the
// path POST /githubs
func (v GithubsResource) Create(c buffalo.Context) error {
	// Allocate an empty Github
	github := &models.Github{}

	// Bind github to the html form elements
	if err := c.Bind(github); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(github)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, github))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", T.Translate(c, "github.created.success"))
	// and redirect to the githubs index page
	return c.Render(201, r.Auto(c, github))
}

// Edit renders a edit form for a Github. This function is
// mapped to the path GET /githubs/{github_id}/edit
func (v GithubsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Github
	github := &models.Github{}

	if err := tx.Find(github, c.Param("github_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, github))
}

// Update changes a Github in the DB. This function is mapped to
// the path PUT /githubs/{github_id}
func (v GithubsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Github
	github := &models.Github{}

	if err := tx.Find(github, c.Param("github_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Github to the html form elements
	if err := c.Bind(github); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(github)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, github))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", T.Translate(c, "github.updated.success"))
	// and redirect to the githubs index page
	return c.Render(200, r.Auto(c, github))
}

// Destroy deletes a Github from the DB. This function is mapped
// to the path DELETE /githubs/{github_id}
func (v GithubsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Github
	github := &models.Github{}

	// To find the Github the parameter github_id is used.
	if err := tx.Find(github, c.Param("github_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(github); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", T.Translate(c, "github.destroyed.success"))
	// Redirect to the githubs index page
	return c.Render(200, r.Auto(c, github))
}
